# Generated by Django 5.2.6 on 2025-09-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='boats')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
