# Generated by Django 5.2.6 on 2025-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='category',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
