# Generated by Django 5.2.6 on 2025-09-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_boat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='boats')),
                ('description', models.CharField(max_length=2000)),
                ('category', models.CharField(default='pending', max_length=200)),
            ],
        ),
    ]
