# Generated by Django 5.2.6 on 2025-09-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(upload_to='rooms'),
        ),
    ]
