# Generated by Django 5.2.6 on 2025-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=2000)),
                ('photo', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
