# Generated by Django 3.2.25 on 2025-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
