# Generated by Django 3.2.25 on 2025-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='noofperson',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
