# Generated by Django 3.2.25 on 2025-10-01 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250930_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
