# Generated by Django 5.2.7 on 2025-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
