# Generated by Django 5.2.7 on 2025-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tariff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_type', models.CharField(choices=[('day', 'Day Cruise'), ('overnight', 'Overnight Cruise')], max_length=20)),
                ('package_type', models.CharField(choices=[('deluxe', 'Deluxe'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('time_slot', models.CharField(blank=True, max_length=50)),
                ('is_special', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('ac_available', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='menu')),
            ],
        ),
    ]
