# Generated by Django 5.2.7 on 2025-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ac_available',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_special',
            field=models.CharField(default=False),
        ),
    ]
