# Generated by Django 5.2.7 on 2025-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_menuitem_ac_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
