# Generated by Django 5.2.7 on 2025-10-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_menuitem_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ac_available',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_special',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
