# Generated by Django 5.2.7 on 2025-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_menuitem_ac_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
