# Generated by Django 5.2.7 on 2026-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_boatbooking_packagebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=50)),
                ('type', models.CharField(choices=[('DayCruise', 'DayCruise'), ('OvernightCruise', 'OvernightCruise')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_people', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_person_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_person_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
